title: Frauke's website
description: > # this means to ignore newlines until "baseurl:"
  This is a personal website for Frauke Rohden.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://fraukero.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: FraukeRohden #if your site has a twitter account, enter it here

# Author Settings
author: Frauke Rohden # add your name
author-img:  # add your photo
about-author: I am a PhD candidate at the University of Oslo. # add description
social-twitter: FraukeRohden # add your Twitter handle
social-facebook: frauke.rohden # add your Facebook handle
social-github: fraukero # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
